In [107]:
import pandas as pd
import numpy as np

In [108]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\pc\pycharmprojects\django\venv\lib\site-packages (1.4.4)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\pc\pycharmprojects\django\venv\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.21.0 in c:\users\pc\pycharmprojects\django\venv\lib\site-packages (from pandas) (1.23.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\pc\pycharmprojects\django\venv\lib\site-packages (from pandas) (2022.2.1)
Requirement already satisfied: six>=1.5 in c:\users\pc\pycharmprojects\django\venv\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [109]:
df = pd.read_csv('weather.csv', encoding='utf8', on_bad_lines='skip', sep=';')

In [110]:
df.head(10)

,Местное время в Харькове (аэропорт),T,Po,P,Pa,U,DD,Ff,ff10,ff3,...,Cm,Ch,VV,Td,RRR,tR,E,Tg,E',sss
0,01.01.2017 23:00,-2.0,744.5,759.1,-0.5,100.0,"Ветер, дующий с юго-запада",4,NaN,NaN,...,NaN,NaN,0.5,-2.0,NaN,NaN,NaN,NaN,NaN,NaN
1,01.01.2017 20:00,-2.5,745.0,759.6,-0.1,98.0,"Ветер, дующий с юго-запада",3,NaN,NaN,...,NaN,NaN,1.2,-2.8,Следы осадков,12.0,NaN,NaN,NaN,NaN
2,01.01.2017 17:00,-3.3,745.1,759.8,-0.4,99.0,"Ветер, дующий с юго-запада",2,NaN,NaN,...,NaN,NaN,0.7,-3.4,NaN,NaN,NaN,NaN,NaN,NaN
3,01.01.2017 14:00,-3.8,745.5,760.2,-0.7,96.0,"Ветер, дующий с западо-юго-запада",3,NaN,NaN,...,NaN,NaN,2.8,-4.3,NaN,NaN,NaN,NaN,NaN,NaN
4,01.01.2017 11:00,-4.1,746.2,760.9,-0.5,96.0,"Ветер, дующий с западо-юго-запада",3,NaN,NaN,...,NaN,NaN,2.8,-4.6,NaN,NaN,NaN,NaN,NaN,NaN
5,01.01.2017 8:00,-5.4,746.7,761.5,-0.2,98.0,"Ветер, дующий с юго-запада",3,NaN,NaN,...,NaN,NaN,2.8,-5.7,Следы осадков,12.0,NaN,NaN,Ровный слой слежавшегося или мокрого снега пок...,9
6,01.01.2017 5:00,-4.6,746.9,761.7,-1.5,100.0,"Ветер, дующий с юго-юго-запада",3,NaN,NaN,...,NaN,NaN,0.8,-4.6,NaN,NaN,NaN,NaN,NaN,NaN
7,01.01.2017 2:00,-4.8,748.4,763.3,-1.2,98.0,"Ветер, дующий с юго-запада",3,NaN,NaN,...,NaN,NaN,1.7,-5.1,Следы осадков,6.0,NaN,NaN,NaN,NaN
8,31.12.2016 23:00,-4.8,749.6,764.5,-1.1,96.0,"Ветер, дующий с западо-юго-запада",3,NaN,NaN,...,NaN,NaN,2.4,-5.4,NaN,NaN,NaN,NaN,NaN,NaN
9,31.12.2016 20:00,-6.0,750.7,765.7,-0.7,92.0,"Ветер, дующий с юго-запада",3,NaN,NaN,...,NaN,NaN,5,-7.1,NaN,NaN,NaN,NaN,NaN,NaN

In [111]:
df['month'] = pd.DatetimeIndex(df['Местное время в Харькове (аэропорт)']).month
df['day'] = pd.DatetimeIndex(df['Местное время в Харькове (аэропорт)']).day
df['week'] = pd.to_datetime(df['Местное время в Харькове (аэропорт)']).dt.isocalendar().week

In [112]:
# day with the highest temp
df.loc[df.groupby(["day"])["T"].idxmax()]

,Местное время в Харькове (аэропорт),T,Po,P,Pa,U,DD,Ff,ff10,ff3,...,Td,RRR,tR,E,Tg,E',sss,month,day,week
2840,12.01.2016 20:00,4.9,728.8,742.8,-2.2,95.0,"Ветер, дующий с юга",10,NaN,NaN,...,4.2,6,12.0,NaN,NaN,NaN,NaN,12,1,48
2667,03.02.2016 11:00,4.1,742.3,756.5,-0.8,82.0,"Ветер, дующий с юго-юго-запада",7,NaN,NaN,...,1.3,NaN,NaN,NaN,NaN,NaN,NaN,3,2,9
2386,09.03.2016 14:00,12.3,751.6,765.6,-0.6,54.0,"Ветер, дующий с востока",6,NaN,NaN,...,3.3,NaN,NaN,NaN,NaN,NaN,NaN,9,3,35
2138,09.04.2016 15:00,24.3,744.7,757.9,-1.0,27.0,"Ветер, дующий с юго-востока",7,NaN,NaN,...,4.3,NaN,NaN,NaN,NaN,NaN,NaN,9,4,35
1891,10.05.2016 15:00,23.3,750.1,763.5,-1.6,35.0,"Ветер, дующий с востоко-северо-востока",2,NaN,NaN,...,6.9,Следы осадков,6.0,NaN,NaN,NaN,NaN,10,5,40
1683,05.06.2016 15:00,25.5,742.1,755.3,-0.8,33.0,"Ветер, дующий с западо-юго-запада",6,NaN,NaN,...,8.1,NaN,NaN,NaN,NaN,NaN,NaN,5,6,18
1451,04.07.2016 15:00,29.5,743.4,756.4,-0.8,39.0,"Ветер, дующий с западо-юго-запада",5,NaN,NaN,...,14.0,NaN,NaN,NaN,NaN,NaN,NaN,4,7,14
1180,07.08.2016 12:00,33.6,747.0,759.9,-0.6,25.0,"Ветер, дующий с северо-северо-востока",1,NaN,NaN,...,11.2,NaN,NaN,NaN,NaN,NaN,NaN,7,8,27
947,05.09.2016 15:00,29.1,745.7,758.8,-1.0,30.0,"Ветер, дующий с юго-юго-запада",5,NaN,NaN,...,9.8,NaN,NaN,NaN,NaN,NaN,NaN,5,9,19
739,01.10.2016 15:00,23.4,750.8,764.2,-0.4,49.0,"Ветер, дующий с юго-юго-запада",7,NaN,NaN,...,12.2,NaN,NaN,NaN,NaN,NaN,NaN,1,10,1
443,07.11.2016 14:00,15.7,739.6,753.2,-1.2,75.0,"Ветер, дующий с юга",7,NaN,NaN,...,11.3,NaN,NaN,NaN,NaN,NaN,NaN,7,11,28
179,10.12.2016 14:00,3.8,739.3,753.5,-0.5,90.0,"Ветер, дующий с западо-юго-запада",6,NaN,NaN,...,2.3,Следы осадков,6.0,NaN,NaN,NaN,NaN,10,12,41
1379,13.07.2016 15:00,31.4,748.2,761.2,-0.7,32.0,"Ветер, дующий с юго-юго-запада",3,NaN,NaN,...,12.6,NaN,NaN,NaN,NaN,NaN,NaN,7,13,28
1371,14.07.2016 15:00,33.7,745.6,758.5,-0.7,28.0,"Ветер, дующий с юго-юго-запада",5,NaN,NaN,...,12.9,NaN,NaN,NaN,NaN,NaN,NaN,7,14,28
1363,15.07.2016 15:00,36.0,745.7,758.5,-0.1,26.0,"Ветер, дующий с юга",3,NaN,NaN,...,13.8,NaN,NaN,NaN,NaN,NaN,NaN,7,15,28
1355,16.07.2016 15:00,36.6,746.7,759.4,-0.3,19.0,"Ветер, дующий с юго-востока",4,NaN,NaN,...,9.7,NaN,NaN,NaN,NaN,NaN,NaN,7,16,28
1347,17.07.2016 15:00,38.4,745.2,757.9,-0.7,21.0,"Ветер, дующий с юго-юго-востока",6,NaN,NaN,...,12.6,NaN,NaN,NaN,NaN,NaN,NaN,7,17,28
1339,18.07.2016 15:00,37.2,737.4,750.0,-1.9,21.0,"Ветер, дующий с юго-юго-востока",9,NaN,NaN,...,11.7,NaN,NaN,NaN,NaN,NaN,NaN,7,18,29
1570,19.06.2016 18:00,28.7,750.8,764.0,-0.2,44.0,"Ветер, дующий с западо-юго-запада",6,NaN,NaN,...,15.4,NaN,NaN,NaN,NaN,NaN,NaN,6,19,24
1075,20.08.2016 15:00,28.1,750.1,763.3,0.0,40.0,"Ветер, дующий с востоко-северо-востока",1,NaN,NaN,...,13.3,NaN,NaN,NaN,NaN,NaN,NaN,8,20,33
1554,21.06.2016 18:00,29.4,754.2,767.4,-0.7,48.0,"Ветер, дующий с востока",2,NaN,NaN,...,17.2,NaN,NaN,NaN,NaN,NaN,NaN,6,21,25
1059,22.08.2016 15:00,34.0,749.0,761.9,-0.4,27.0,"Ветер, дующий с востока",7,NaN,NaN,...,12.5,NaN,NaN,NaN,NaN,NaN,NaN,8,22,34
1051,23.08.2016 15:00,31.9,749.7,762.7,-0.4,22.0,"Ветер, дующий с востока",7,NaN,NaN,...,7.9,NaN,NaN,NaN,NaN,NaN,NaN,8,23,34
1043,24.08.2016 15:00,27.9,745.9,759.0,-0.4,50.0,"Ветер, дующий с юго-юго-запада",1,NaN,NaN,...,16.5,NaN,NaN,NaN,NaN,NaN,NaN,8,24,34
1523,25.06.2016 15:00,27.3,752.6,765.9,-0.4,41.0,"Ветер, дующий с востока",2,NaN,NaN,...,13.0,NaN,NaN,NaN,NaN,NaN,NaN,6,25,25
1515,26.06.2016 15:00,29.8,750.5,763.6,-1.2,38.0,"Ветер, дующий с востоко-юго-востока",2,NaN,NaN,...,13.9,NaN,NaN,NaN,NaN,NaN,NaN,6,26,25
1507,27.06.2016 15:00,31.8,745.3,758.2,-1.1,35.0,"Ветер, дующий с западо-северо-запада",2,NaN,NaN,...,14.6,NaN,NaN,NaN,NaN,NaN,NaN,6,27,26
1259,28.07.2016 15:00,30.5,748.3,761.3,-0.6,34.0,"Ветер, дующий с юго-запада",2,NaN,NaN,...,12.9,NaN,NaN,NaN,NaN,NaN,NaN,7,28,30
1003,29.08.2016 15:00,29.8,750.2,763.3,-0.7,31.0,"Ветер, дующий с востоко-северо-востока",3,NaN,NaN,...,11.1,NaN,NaN,NaN,NaN,NaN,NaN,8,29,35
995,30.08.2016 15:00,31.2,746.6,759.6,-1.4,30.0,"Ветер, дующий с востоко-юго-востока",5,NaN,NaN,...,11.8,NaN,NaN,NaN,NaN,NaN,NaN,8,30,35
1234,31.07.2016 18:00,28.9,746.1,759.1,-0.1,53.0,"Ветер, дующий с северо-северо-востока",4,NaN,NaN,...,18.3,NaN,NaN,NaN,NaN,NaN,NaN,7,31,30

In [113]:
# day with the lowest temp
df.loc[df.groupby(["day"])["T"].idxmin()]

,Местное время в Харькове (аэропорт),T,Po,P,Pa,U,DD,Ff,ff10,ff3,...,Td,RRR,tR,E,Tg,E',sss,month,day,week
2900,05.01.2016 8:00,-22.1,746.2,762.0,-0.3,78.0,"Ветер, дующий с востока",3,NaN,NaN,...,-24.9,Следы осадков,12.0,NaN,NaN,Ровный слой сухого рассыпчатого снега покрывае...,7,5,1,17
2630,08.02.2016 2:00,-8.4,758.8,774.1,0.0,89.0,"Ветер, дующий с юго-востока",3,NaN,NaN,...,-9.9,NaN,NaN,NaN,NaN,NaN,NaN,8,2,31
2365,12.03.2016 5:00,0.8,753.0,767.6,0.0,87.0,"Штиль, безветрие",0,NaN,NaN,...,-1.2,NaN,NaN,NaN,NaN,NaN,NaN,12,3,48
2189,03.04.2016 6:00,2.4,748.0,762.4,0.5,72.0,"Ветер, дующий с западо-северо-запада",5,NaN,NaN,...,-2.2,NaN,NaN,NaN,NaN,NaN,NaN,3,4,9
1958,02.05.2016 6:00,5.5,753.4,767.8,-0.1,91.0,"Ветер, дующий с северо-запада",2,NaN,NaN,...,4.1,NaN,NaN,NaN,NaN,NaN,NaN,2,5,5
1662,08.06.2016 6:00,7.3,749.6,763.8,0.2,79.0,"Ветер, дующий с запада",2,NaN,NaN,...,3.8,NaN,NaN,NaN,NaN,NaN,NaN,8,6,31
1439,06.07.2016 3:00,12.6,747.1,761.0,-0.2,82.0,"Штиль, безветрие",0,NaN,NaN,...,9.5,NaN,NaN,NaN,NaN,NaN,NaN,6,7,23
1166,09.08.2016 6:00,16.2,750.0,763.7,0.4,72.0,"Ветер, дующий с северо-северо-запада",3,NaN,NaN,...,11.2,NaN,NaN,NaN,NaN,NaN,NaN,9,8,36
910,10.09.2016 6:00,9.2,752.2,766.3,0.6,88.0,"Ветер, дующий с северо-северо-запада",1,NaN,NaN,...,7.3,NaN,NaN,NaN,NaN,NaN,NaN,10,9,40
649,12.10.2016 21:00,4.5,755.6,770.1,0.0,68.0,"Ветер, дующий с востоко-северо-востока",6,NaN,NaN,...,-0.9,NaN,NaN,NaN,NaN,NaN,NaN,12,10,49
456,05.11.2016 23:00,-1.9,753.4,768.2,-0.2,90.0,"Ветер, дующий с юго-востока",2,NaN,NaN,...,-3.4,NaN,NaN,NaN,NaN,NaN,NaN,5,11,19
200,07.12.2016 23:00,-14.9,760.0,775.7,-0.6,88.0,"Ветер, дующий с западо-юго-запада",3,NaN,NaN,...,-16.4,NaN,NaN,NaN,NaN,NaN,NaN,7,12,28
157,13.12.2016 8:00,-12.7,750.2,765.6,1.3,79.0,"Ветер, дующий с северо-северо-запада",5,NaN,NaN,...,-15.6,Следы осадков,12.0,NaN,NaN,Ровный слой сухого рассыпчатого снега покрывае...,9,12,13,50
149,14.12.2016 8:00,-9.2,752.1,767.2,0.3,92.0,"Ветер, дующий с юга",2,NaN,NaN,...,-10.3,0.2,12.0,NaN,NaN,Ровный слой сухого рассыпчатого снега покрывае...,10,12,14,50
136,15.12.2016 23:00,-12.5,756.1,771.6,1.3,86.0,"Ветер, дующий с северо-северо-запада",2,NaN,NaN,...,-14.4,NaN,NaN,NaN,NaN,NaN,NaN,12,15,50
128,16.12.2016 23:00,-17.1,760.9,776.8,-0.1,89.0,"Ветер, дующий с востоко-юго-востока",2,NaN,NaN,...,-18.5,NaN,NaN,NaN,NaN,NaN,NaN,12,16,50
126,17.12.2016 5:00,-17.6,759.9,775.7,-0.6,85.0,"Ветер, дующий с востоко-юго-востока",2,NaN,NaN,...,-19.5,NaN,NaN,NaN,NaN,NaN,NaN,12,17,50
2798,18.01.2016 2:00,-6.9,741.9,756.7,-0.4,89.0,"Ветер, дующий с севера",7,NaN,NaN,...,-8.5,6,6.0,NaN,NaN,NaN,NaN,1,18,3
2785,19.01.2016 17:00,-6.3,736.9,751.6,1.8,84.0,"Ветер, дующий с запада",4,NaN,NaN,...,-8.6,NaN,NaN,NaN,NaN,NaN,NaN,1,19,3
96,20.12.2016 23:00,-12.4,762.2,777.8,0.9,72.0,"Ветер, дующий с северо-северо-востока",2,NaN,NaN,...,-16.4,NaN,NaN,NaN,NaN,NaN,NaN,12,20,51
95,21.12.2016 2:00,-14.7,762.7,778.4,0.5,80.0,"Ветер, дующий с северо-востока",2,NaN,NaN,...,-17.4,NaN,NaN,NaN,NaN,NaN,NaN,12,21,51
2764,22.01.2016 8:00,-15.1,753.7,769.3,1.1,100.0,"Ветер, дующий с северо-северо-запада",1,NaN,NaN,...,-15.1,NaN,NaN,NaN,NaN,Неровный слой сухого рассыпчатого снега покрыв...,34,1,22,3
2752,23.01.2016 20:00,-13.9,758.8,774.4,0.5,85.0,"Ветер, дующий с юго-запада",1,NaN,NaN,...,-15.9,Следы осадков,12.0,NaN,NaN,NaN,NaN,1,23,3
2743,24.01.2016 23:00,-19.1,759.6,775.6,-0.2,82.0,"Штиль, безветрие",0,NaN,NaN,...,-21.4,NaN,NaN,NaN,NaN,NaN,NaN,1,24,3
2740,25.01.2016 8:00,-23.4,759.1,775.3,0.0,87.0,"Штиль, безветрие",0,NaN,NaN,...,-25.0,Следы осадков,12.0,NaN,NaN,Неровный слой сухого рассыпчатого снега покрыв...,35,1,25,4
2733,26.01.2016 5:00,-20.7,755.4,771.4,0.2,82.0,"Ветер, дующий с востоко-юго-востока",3,NaN,NaN,...,-23.0,NaN,NaN,NaN,NaN,NaN,NaN,1,26,4
2726,27.01.2016 2:00,-9.0,755.4,770.6,-1.8,89.0,"Ветер, дующий с юга",5,NaN,NaN,...,-10.5,Следы осадков,6.0,NaN,NaN,NaN,NaN,1,27,4
526,28.10.2016 6:00,-5.0,762.4,777.5,0.2,93.0,"Ветер, дующий с западо-северо-запада",1,NaN,NaN,...,-6.0,NaN,NaN,NaN,NaN,NaN,NaN,10,28,43
264,29.11.2016 23:00,-4.9,749.3,764.2,1.1,91.0,"Ветер, дующий с северо-северо-востока",5,NaN,NaN,...,-6.2,NaN,NaN,NaN,NaN,NaN,NaN,11,29,48
256,30.11.2016 23:00,-14.0,751.0,766.4,-0.6,90.0,"Ветер, дующий с юго-юго-востока",2,NaN,NaN,...,-15.3,NaN,NaN,NaN,NaN,NaN,NaN,11,30,48
13,31.12.2016 8:00,-9.4,756.3,771.6,-0.4,95.0,"Ветер, дующий с юго-юго-запада",3,NaN,NaN,...,-10.1,NaN,NaN,NaN,NaN,Ровный слой слежавшегося или мокрого снега пок...,9,12,31,52

In [114]:
df_month = df.groupby('month').mean()

In [115]:
# month with the highest average wind speed
df_month['Ff'].idxmax()

11

In [116]:
# month with the lowest average temperature
df_month['T'].idxmin()

1

In [117]:
# month with the highest average temperature
df_month['T'].idxmax()

7

In [118]:
# week with the highest amount of rain 
df['RRR'] = pd.to_numeric(df['RRR'], errors='coerce')
df.sort_values(['RRR'],ascending=False, inplace=True)
df

,Местное время в Харькове (аэропорт),T,Po,P,Pa,U,DD,Ff,ff10,ff3,...,Td,RRR,tR,E,Tg,E',sss,month,day,week
1737,29.05.2016 21:00,16.6,744.7,758.3,1.1,85.0,"Ветер, дующий с востока",2,NaN,NaN,...,14.0,42.0,12.0,NaN,NaN,NaN,NaN,5,29,21
1477,01.07.2016 9:00,22.2,746.7,760.0,0.3,73.0,"Ветер, дующий с северо-востока",4,NaN,NaN,...,17.0,39.0,12.0,NaN,NaN,NaN,NaN,1,7,1
1739,29.05.2016 15:00,18.5,743.8,757.3,1.0,92.0,"Ветер, дующий с юго-востока",5,NaN,22.0,...,17.2,35.0,6.0,NaN,NaN,NaN,NaN,5,29,21
1857,14.05.2016 21:00,14.1,735.1,748.7,0.6,90.0,"Ветер, дующий с юго-юго-запада",5,NaN,NaN,...,12.5,30.0,12.0,NaN,NaN,NaN,NaN,5,14,19
1479,01.07.2016 3:00,20.0,745.5,758.9,0.2,85.0,"Ветер, дующий с севера",3,NaN,NaN,...,17.4,29.0,6.0,NaN,NaN,NaN,NaN,1,7,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2929,01.01.2016 17:00,-13.0,757.3,772.8,0.7,79.0,"Ветер, дующий с северо-востока",3,NaN,NaN,...,-15.9,NaN,NaN,NaN,NaN,NaN,NaN,1,1,53
2930,01.01.2016 14:00,-12.0,756.6,772.0,-0.1,70.0,"Ветер, дующий с северо-северо-востока",4,NaN,NaN,...,-16.4,NaN,6.0,NaN,NaN,NaN,NaN,1,1,53
2931,01.01.2016 11:00,-12.3,756.7,772.1,0.5,71.0,"Ветер, дующий с востока",5,NaN,NaN,...,-16.5,NaN,NaN,NaN,NaN,NaN,NaN,1,1,53
2933,01.01.2016 5:00,-12.1,755.9,771.4,0.1,79.0,"Ветер, дующий с северо-северо-востока",3,NaN,NaN,...,-15.1,NaN,NaN,NaN,NaN,NaN,NaN,1,1,53
2934,01.01.2016 2:00,-11.8,755.8,771.2,-0.3,79.0,"Ветер, дующий с северо-северо-востока",3,NaN,NaN,...,-14.7,NaN,6.0,NaN,NaN,NaN,NaN,1,1,53